version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - node_modules
    environment:
      - NODE_ENV=development
  node_modules:
    image: node:18
    volumes:
      - /app/node_modules